# Generated by Django 5.2.5 on 2025-08-18 12:02

import django.core.validators
import django.db.models.deletion
import recrute.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du poste')),
                ('localisation', models.CharField(max_length=100, verbose_name='Localisation')),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage'), ('FREELANCE', 'Freelance')], max_length=20, verbose_name='Type de contrat')),
                ('categorie', models.CharField(blank=True, help_text='Ex : Informatique, Marketing, etc.', max_length=100, verbose_name='Catégorie')),
                ('description', models.TextField(verbose_name='Description du poste')),
                ('profil_recherche', models.TextField(verbose_name='Profil recherché')),
                ('publie', models.BooleanField(default=True, verbose_name='Publié')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Postuler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('lettre_motivation', models.TextField(blank=True, null=True, verbose_name='Lettre de motivation')),
                ('cv', models.FileField(help_text='Seuls les fichiers PDF, DOC et DOCX sont autorisés.', upload_to=recrute.models.cv_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='CV')),
                ('date_candidature', models.DateTimeField(auto_now_add=True, verbose_name='Date de candidature')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='recrute.travail', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-date_candidature'],
            },
        ),
    ]
